apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: marketly
  labels:
    app: frontend
    app.kubernetes.io/part-of: marketly
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
