apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: marketly
  labels:
    app: auth-service
    app.kubernetes.io/part-of: marketly
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - name: http
      port: 5001
      targetPort: http
      protocol: TCP
