apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: marketly
  labels:
    app: orders-service
    app.kubernetes.io/part-of: marketly
spec:
  type: ClusterIP
  selector:
    app: orders-service
  ports:
    - name: http
      port: 5003
      targetPort: http
      protocol: TCP
